### ISSUE TITLE
module broken by PDL>=2.040's removal of PDL::Core::at_c

### ISSUE THREAD

**Issue by iynehz** [kmx/pdl-datetime#3]
Now PDL::DateTime uses PDL::Core::at_c https://github.com/kmx/pdl-datetime/blob/631068f86966a170365961acc3e7751cfa362a4a/lib/PDL/DateTime.pm#L409. But that function's removed from PDL since 2.040

See https://github.com/PDLPorters/pdl/commit/96a69e20568456c3c13f5dfc91caea7bc5fbe0b2 . Looks like the fix can be replacing at_c with at_bad_c.

**Comment by mohawk2** [comment]
PDL 2.054 (from Jul 2021) fixes this with a back-compatibility `at_c` alias.
